name: Build, Test, and Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Tools
    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang gcc build-essential

    # Step 3: Run Cppcheck
    - name: Run Cppcheck Static Analysis
      run: |
        cppcheck --enable=all --inconclusive --std=c11 --force --max-configs=1 -I/usr/include main.c 2> cppcheck-results.txt
        if [ -s cppcheck-results.txt ]; then
          echo "Cppcheck found issues:"
          cat cppcheck-results.txt
          exit 1
        else
          echo "No issues found by Cppcheck."
        fi

    # Step 4: Build with AddressSanitizer
    - name: Build with ASan
      run: gcc -fsanitize=address -g -o main main.c

    # Step 5: Run AddressSanitizer
    - name: Run AddressSanitizer
      run: |
        ./main
        exit 0
