name: Cppcheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: cppcheck --enable=all --inconclusive --error-exitcode=1 --force .
