name: Build, Test, and Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install GCC and Make
    - name: Install GCC and Make
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    # Step 3: Install Cppcheck
    - name: Install Cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    # Step 4: Run Cppcheck (Errors in Logs)
    - name: Run Cppcheck Static Analysis
      run: |
        cppcheck --enable=all --inconclusive --std=c11 --template="{file}:{line}: {severity}: {message}" main.c || exit 1

    # Step 5: Build the Project
    - name: Build the Project
      run: |
        make clean
        make VERBOSE=1

    # Step 6: Run the Main Program
    - name: Run Main Program
      run: ./main

    # Optional: Step 7: Check for Warnings in Program Output
    - name: Check for Warnings
      run: |
        ./main | grep -q "Warning" && exit 1 || echo "No warnings found."
